### ISSUE TITLE
Unable to start a custom games match after joining a server

### ISSUE THREAD

**Issue by pistakilla** [momo5502/boiii#153] opened 2023-02-12 18:48 UTC
Once I was able to start a custom games match to check if my CAC are intact, then I joined a server. After I left the server, when I wanted to start a custom games match or a public games match it would load indefinitely until I got a "Lost connection to host" error message. Inorder for me to start one again is to restart the entire game.

**Comment by momo5502** [comment] 2023-02-13 17:48
Duplicate of #137

**Closed by momo5502** 2023-02-13 17:48 UTC
Labels: bug, duplicate
