### ISSUE TITLE
Adding friends    

### ISSUE THREAD

**Issue by rd0881** [momo5502/boiii#549] opened 2023-04-17 05:37 UTC
### Your feature request or suggestion:

Can you pls add an feature which allows us the add friends form steam or add them the social to a custom game on multiplayer or zombies so that we don't need to connect to a pubic server to play with friends.

**Comment by SwordSWD** [comment] 2023-04-17 05:43
this is a duplicate of #175

**Comment by rd0881** [comment] 2023-04-17 05:47
SO are they working on adding this type of feature or not

**Closed** 2023-04-17 05:56 UTC
Labels: duplicate, feature
