### ISSUE TITLE
Possibility of loading more than 1 mod

### ISSUE THREAD

**Issue by Joka333a** [momo5502/boiii#189] opened 2023-02-16 23:42 UTC
Q:  Unlike original steam bo3,will it be possible to load more than 1 mod without the need of the boring combining process? I hope this feature will be present somehow.

**Comment by diamante0018** [comment] 2023-02-17 10:35
Duplicate of #99 
Please take 10 seconds to search if a similar issue has already been opened before opening a new one.

**Closed by diamante0018** 2023-02-17 10:35 UTC
Labels: duplicate, feature
