### ISSUE TITLE
FPS Problem

### ISSUE THREAD

**Issue by RywaZ** [momo5502/boiii#181] opened 2023-02-16 17:42 UTC
I noticed that I had a big loss of fps I know that normally it was fixed but I think it's back

![image](https://user-images.githubusercontent.com/124745850/219446415-b60f3c87-065f-40d1-91cf-66215b3ab721.png)

https://streamable.com/bl25j6
https://streamable.com/6nx4ct

**Comment by momo5502** [comment] 2023-02-16 17:51
this is highly likely something on your system

**Comment by momo5502** [comment] 2023-02-16 17:51
to analyze this i need samples, for example using very sleepy: https://github.com/VerySleepy/verysleepy

**Comment by RywaZ** [comment] 2023-02-16 17:54
> to analyze this i need samples, for example using very sleepy: https://github.com/VerySleepy/verysleepy

how to use very sleepy

**Comment by RywaZ** [comment] 2023-02-16 18:00
my game just crashed 2 times

**Comment by RywaZ** [comment] 2023-02-16 18:00
![image](https://user-images.githubusercontent.com/124745850/219449427-5d9da123-e4cb-4321-9fbd-0edc5e462536.png)

**Comment by momo5502** [comment] 2023-02-16 18:04
upload the minidumps in a separate issue. but not those, they're empty, upload the correct ones.

**Comment by momo5502** [comment] 2023-02-16 18:06
> > to analyze this i need samples, for example using very sleepy: https://github.com/VerySleepy/verysleepy
> 
> how to use very sleepy

run it, run boiii, click on boiii in very sleepy and profile it until you see fps drops, then send me the result

**Comment by RywaZ** [comment] 2023-02-16 18:09
[boiii-crash-2023-02-15-21-17-18.zip](https://github.com/momo5502/boiii/files/10759183/boiii-crash-2023-02-15-21-17-18.zip)
[boiii-crash-2023-02-16-18-37-23.zip](https://github.com/momo5502/boiii/files/10759184/boiii-crash-2023-02-16-18-37-23.zip)
[boiii-crash-2023-02-16-18-57-10.zip](https://github.com/momo5502/boiii/files/10759185/boiii-crash-2023-02-16-18-57-10.zip)
[boiii-crash-2023-02-16-18-59-22.zip](https://github.com/momo5502/boiii/files/10759186/boiii-crash-2023-02-16-18-59-22.zip)

**Comment by RywaZ** [comment] 2023-02-16 18:20
it's weird now I don't have the problem while I didn't change anything on my system

**Comment by RywaZ** [comment] 2023-02-16 18:22
it's weird now I don't have the problem while I didn't change anything on my system

**Comment by momo5502** [comment] 2023-02-16 18:30
please create a separate issue for the crashes. mixing up two different issues in one github issue makes it hard for me to keep track of everything

**Comment by momo5502** [comment] 2023-02-16 18:36
hold up
i fucked up

**Comment by momo5502** [comment] 2023-02-16 18:37
let me push a fix and then try again in ~30 minutes, maybe the crashes are gone

**Comment by RywaZ** [comment] 2023-02-16 18:40
> let me push a fix and then try again in ~30 minutes, maybe the crashes are gone
Okay

**Comment by RywaZ** [comment] 2023-02-17 17:21
why every time I open very sleepy my game crashes?

**Comment by momo5502** [comment] 2023-02-18 07:50
Can you please verify this still occurs? Might have been a duplicate of #167

**Comment by momo5502** [comment] 2023-02-18 07:51
This sets a registry key, so you might have to restart the game once you launched it with the new update

**Comment by RywaZ** [comment] 2023-02-18 14:22
I always have the problem of fps I noticed that when I open very sleepy but FPS come back but the problem is that every time my game crashes because of very sleepy I do not know why so I can not send you the results

> This sets a registry key, so you might have to restart the game once you launched it with the new update

**Comment by RywaZ** [comment] 2023-02-18 14:32
https://streamable.com/fc8spa

**Comment by RywaZ** [comment] 2023-02-18 14:33
![image](https://user-images.githubusercontent.com/124745850/219871447-64d98e51-352d-4683-8a87-6d4780cf6d59.png)

**Comment by RywaZ** [comment] 2023-02-18 14:40
I never had this fps problem before

**Comment by RywaZ** [comment] 2023-03-05 18:30
you can close this issue the problem have been fixed :)

**Closed** 2023-03-05 18:31 UTC
Labels: bug, needs info
