### ISSUE TITLE
Easy download of custom maps for dedicated servers

### ISSUE THREAD

**Issue by SpartanOxide** [momo5502/boiii#625] opened 2023-05-01 09:24 UTC
### Duplicate Issue Check

- [ ] #626

### Your feature request or suggestion:

I would like to propose a feature I know it would be hard to develop and implement, but a dedicated tool to download mods/custom maps for dedicated servers on VPS/dedicated Servers. You can use SteamCMD to download maps from the workshop but 90% of the time downloads of custom maps timeout when using SteamCMD, I presume because of the size of the maps. This would be a good application and tool that is packed in with the server files.

**Comment by SwordSWD** [comment] 2023-05-01 10:17
Duplicate of #185

**Comment by Dss0** [comment] 2023-05-01 11:38
i just tried downloading a couple of large maps with steam cmd and there were no issues. alternatively you can transfer them from your pc to your vps. the server does not need anything besides these files so size shouldn't be an issue:

![8d8b97ee0f938a30aa6d4aa9b9f53679](https://user-images.githubusercontent.com/7338300/235446677-343591cb-e2bb-4397-88db-8f9099cadca0.png)

**Comment by diamante0018** [comment] 2023-05-01 13:43
Duplicate of #185

**Closed by diamante0018** 2023-05-01 13:43 UTC
Labels: feature
