### ISSUE TITLE
cant figure out how to change my name

### ISSUE THREAD

**Issue by adamhernali** [momo5502/boiii#422] opened 2023-04-01 18:25 UTC
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

its just a name change 

### Expected Result

changing name

### Actual Result

nothing

### (Optional) Proof and Additional Information

ok

### Severity/Priority

High/Critical

**Comment by D3AL1O** [comment] 2023-04-01 18:32
/name [insert name here] then restart the game.

**Comment by diamante0018** [comment] 2023-04-01 19:02
Follow the advice you were given. Additionally this is possibly a duplicate of #406 .
I don't think you actually checked whenever a similar issue was already open when you opened this.

**Closed by diamante0018** 2023-04-01 19:02 UTC
Labels: bug

**Comment by RyhZM** [comment] 2023-04-01 23:11
brother.... 😭
