### ISSUE TITLE
Game Crash on startup

### ISSUE THREAD

**Issue by lxMysticxl** [momo5502/boiii#617] opened 2023-04-29 15:12 UTC
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. I open the route directory file for my BO3 game on steam
2. Double click the BOIII client 
3. And it crashes when I click "Play" on the BOIII client after it takes a couple of seconds to load

### Expected Result

The client should work normally and I should be able to play BO3 on the BOIII client instead.

### Actual Result

The application crashes with no error code. 

### Severity/Priority

High/Critical

**Comment by pistakilla** [comment] 2023-04-29 15:18
Duplicate of #316

**Closed** 2023-04-29 15:36 UTC
Labels: bug
