### ISSUE TITLE
Shadows of Evil Crash when someone fails to join

### ISSUE THREAD

**Issue by HackersinSpace** [momo5502/boiii#666] opened 2023-05-09 09:54 UTC
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

This happens no matter what mod is loaded. And also vanilla so no mods.
1. Host via Radmin VPN
2. Load up Shadows of Evil
3. Have friends connect via /connect {Host IP Here}
4. 1 person connects successfully and other fails to load which makes them invisible and doesn't show up on scoreboard.
5. Invisible player tries to disconnect via command /disconnect and host crashes.
[boiii-crash-2023-05-09-04-57-56.zip](https://github.com/momo5502/boiii/files/11429699/boiii-crash-2023-05-09-04-57-56.zip)
[boiii-crash-2023-05-09-04-47-49.zip](https://github.com/momo5502/boiii/files/11429701/boiii-crash-2023-05-09-04-47-49.zip)
[boiii-crash-2023-05-09-04-43-37.zip](https://github.com/momo5502/boiii/files/11429702/boiii-crash-2023-05-09-04-43-37.zip)

### Expected Result

When following instructions to play with people via Radmin VPN you should be able to play Shadows of Evil fine.

### Actual Result

The Host crashes when other player tries disconnecting from lobby after being invisible and cannot spawn into map normally.

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment] 2023-05-09 09:57
Duplicate of #640

**Closed by diamante0018** 2023-05-09 09:57 UTC
Labels: bug
