### ISSUE TITLE
Is it possible to start boiii with additional parameters in the startup item?

### ISSUE THREAD

**Issue by liveskai** [momo5502/boiii#208] opened 2023-02-20 07:49 UTC
![image](https://user-images.githubusercontent.com/54350655/220044435-ba9a990f-1739-4aae-bfc7-d43ffeea7ecf.png)

**Comment by momo5502** [comment] 2023-02-20 07:52
I assume this is a duplicate of #205, however I can't read the hieroglyphs you posted there bro.

**Closed by momo5502** 2023-02-20 07:52 UTC
Labels: duplicate, feature
