### ISSUE TITLE
Zombies Weapon Kits - DLC Weapons

### ISSUE THREAD

**Issue by ItzAreeb** [momo5502/boiii#496] opened 2023-04-11 00:35 UTC
### Duplicate Issue Check

- [ ] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

It would be nice if the extra DLC weapons like the FFAR or 1911 in zombies were added to the weapon kits menu so that the attachments and camos can be customized if possible.

**Comment by JariKCoding** [comment] 2023-04-11 00:38
Duplicate of #400

**Comment by diamante0018** [comment] 2023-04-11 07:36
Duplicate of #400

**Closed by diamante0018** 2023-04-11 07:36 UTC
Labels: feature
