### ISSUE TITLE
Random Crashes when running 2 dedicated servers.

### ISSUE THREAD

**Issue by SwordSWD** [momo5502/boiii#493] opened 2023-04-10 18:21 UTC
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Windows Server 2019, Windows Server 2016

### Reproducibility Rate

Low: The bug has only occurred once or a small number of times

### Steps to Reproduce

1. Run the server for some amount of time like for 3 or 4 hours

I have only 2 servers running, MP and ZM 

### Expected Result

Not random crashes.

### Actual Result

Random Crashes

### (Optional) Proof and Additional Information

[boiii-crash-2023-04-10-04-19-56.zip](https://github.com/momo5502/boiii/files/11192846/boiii-crash-2023-04-10-04-19-56.zip)
[boiii-crash-2023-04-10-14-10-06.zip](https://github.com/momo5502/boiii/files/11192847/boiii-crash-2023-04-10-14-10-06.zip)

### Severity/Priority

Medium

**Comment by momo5502** [comment] 2023-04-12 16:54
pretty sure that's a duplicate of #486

**Closed by momo5502** 2023-04-12 16:54 UTC
Labels: bug, duplicate
