### ISSUE TITLE
ZM: Wave End/Start Stings completely halt playback of Music when connected to Dedicated Servers

### ISSUE THREAD

**Issue by MotoLegacy** [momo5502/boiii#473] opened 2023-04-09 04:29 UTC
### Bug Type

Dedicated Server

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

SteamOS

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Connect to a Zombies match on a Dedicated Server
2. Complete the sidequest steps to trigger the Music Easter Egg
3. Kill a Zombie to trigger a Round end while the Music is playing

### Expected Result

Round stings do not play while Music is being played back, matched behavior with Private Matches.

### Actual Result

The Round stings interrupt and halt Music playback, does not continue after they are finished.

### (Optional) Proof and Additional Information

Ending a Round in a Private Match:

https://user-images.githubusercontent.com/26030250/230754400-7755d39d-5447-4a35-b0df-8333ec493de2.mp4

<br>
<br>

Ending a Round when connected to a Dedicated Server:

https://user-images.githubusercontent.com/26030250/230754409-4be1d70d-d08a-4886-ab48-104fdc0d5a7a.mp4

### Severity/Priority

Minor

**Comment by diamante0018** [comment] 2023-04-09 14:14
This is a duplicate of #235
Because zombie dedicated servers were not intended by 3arc they can't handle sounds.

**Closed by diamante0018** 2023-04-09 14:14 UTC
Labels: bug
