### ISSUE TITLE
Game freezes when you leave a server browser match if you join from a different game mode e.g. Zombies

### ISSUE THREAD

**Issue by ethanjones99** [momo5502/boiii#157] opened 2023-02-13 12:24 UTC
So I noticed that I would get stuck on a checkerboard screen if I left an mp server browser game if I opened the server browser from a different game mode. I tried zombies and campaign, and they both freeze, which requires me to alt f4. The console can still be opened on the screen, so it doesn't seem frozen entirely.

**Comment by ethanjones99** [comment] 2023-02-13 12:28
https://imgur.com/a/r5RMgzp

screenshots of the console and game

**Comment by momo5502** [comment] 2023-02-14 06:29
This is highly likely a duplicate of #149, so I'm gonna close this one for now.

**Closed by momo5502** 2023-02-14 06:29 UTC
Labels: bug, duplicate
