### ISSUE TITLE
1. Currently with the unlock menu additional class sets are not unlocked unless you increment your prestige by one level, play a game to get the last 1xp then prestige reset naturally.

### ISSUE THREAD

**Issue by Farazzles** [momo5502/boiii#526] opened 2023-04-13 12:51 UTC
1. Currently with the unlock menu additional class sets are not unlocked unless you increment your prestige by one level, play a game to get the last 1xp then prestige reset naturally. 
2. The above method gives an additional class "sets", but I do not think it give an additional "class #" options. 
3. The above method does not apply to custom games.

This PR just unlocks classes regardless of level. I can't see anyone wanting just 5 classes.

![image](https://user-images.githubusercontent.com/122710241/229758110-a8522908-e62b-4a50-b70c-02c407499d51.png)

_Originally posted by @WantedDV in https://github.com/momo5502/boiii/issues/440#issuecomment-1495698319_

**Comment by diamante0018** [comment] 2023-04-13 14:13
Duplicate of #440

**Closed by diamante0018** 2023-04-13 14:13 UTC
