### ISSUE TITLE
HUD Display Area 

### ISSUE THREAD

**Issue by jigguz** [momo5502/boiii#554] opened 2023-04-18 04:48 UTC
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Black Ops 3 already has this feature in the console versions, however It would be nice to have an option in Video Settings to adjust the display area of the HUD and maybe the menus/ui

**Comment by VladWinner** [comment] 2023-04-18 07:26
For now you can just use `safeArea_horizontal` and `safeArea_vertical` commands although their values will reset after restarting the game.

**Comment by momo5502** [comment] 2023-04-18 07:31
I don't think adding them to the menu is worth the time, unless someone wants to do it.
But making the dvars archived is a good thing to do.

**Comment by VladWinner** [comment] 2023-04-21 10:43
> adding them to the menu

Here is my simple implementation (no preview, unlike consoles)
![image](https://user-images.githubusercontent.com/13555921/233615625-e7db7cbb-653b-4d7c-8a25-bce2501efd5b.png)

But I need help to get the current values of 'Game' submenu items to show correctly again.
(I had to add a header inside `CoD.StartMenu_Options_PC_Graphics_Game.new` function).

data\ui_scripts\graphics_settings\init.lua: [graphics_settings.zip](https://github.com/momo5502/boiii/files/11294962/graphics_settings.zip)

**Comment by diamante0018** [comment] 2023-05-09 11:56
Duplicate of #312

**Closed by diamante0018** 2023-05-09 11:56 UTC
Labels: feature
