### ISSUE TITLE
Tracking not working on certain guns

### ISSUE THREAD

**Issue by Nheyah** [momo5502/boiii#607] opened 2023-04-27 17:08 UTC
### Bug Type

Other

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

No steps, just some guns dont level up/track camo challenges. both my kuda and kn44 level up, but my locus, hvk, weevil, and brecci dont level up or track camo challenges. No idea whats caused this. 

### Expected Result

Certain guns dont level up or track challenges

### Actual Result

Certain guns dont level up or track challenges

### Severity/Priority

Medium

**Comment by pistakilla** [comment] 2023-04-27 17:33
Make sure you finish the match before leaving it. Stats don't count if you disconnect yourself midgame, especially if you force dc yourself via console using `disconnect` or `killserver`.

**Comment by diamante0018** [comment] 2023-04-28 14:18
Duplicate of #471 
Pretty sure

**Closed by diamante0018** 2023-04-28 14:18 UTC
Labels: bug
