### ISSUE TITLE
Joining via IP causes black screen

### ISSUE THREAD

**Issue by HomamMousa** [momo5502/boiii#481] opened 2023-04-10 06:17 UTC
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

Joining to a game in a local network
or
Joining to a second instance on the same pc:
![image](https://user-images.githubusercontent.com/129157644/230839144-1fde7147-08ac-4e78-bea8-b8f7f262a40f.png)

### Expected Result

The game (or game instances) should connect to the game without crashing

### Actual Result

Joining via IP causes a black screen in Zombies and in multiplayer the instance is stuck in a loading screen

Joining in Multiplayer:
![image](https://user-images.githubusercontent.com/129157644/230837087-eca419dd-c822-4606-a088-7cc9aa3ca42f.png)

Joining in Zombies:
![image](https://user-images.githubusercontent.com/129157644/230837360-3823e26b-1517-412e-b884-af8555ecfe13.png)

**Joining in a game with splitscreen enabled:**
![image](https://user-images.githubusercontent.com/129157644/230837888-b7b29a17-7987-4fdf-b311-bb4dc8e810c9.png)

### Severity/Priority

High/Critical

**Comment by momo5502** [comment] 2023-04-10 06:53
Feels like a duplicate of this: #480

**Closed** 2023-04-10 07:08 UTC
Labels: bug, duplicate
