### ISSUE TITLE
(If possible) add DLC weapons to ZM weapon kits

### ISSUE THREAD

**Issue by BladedChild** [momo5502/boiii#615] opened 2023-04-28 22:27 UTC
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

I just think it would be cool to see DLC weapons (and even the MR6) in the weapons kits in zombies. That way when you get something like the PPSH or Razorback it won't look as bland as everything else in your kits

**Comment by diamante0018** [comment] 2023-04-29 09:47
Duplicate of #400

**Closed by diamante0018** 2023-04-29 09:47 UTC
Labels: feature

**Comment by BladedChild** [comment] 2023-04-30 15:30
Ooh sorry about that! Guess that slipped by me when going through
