### ISSUE TITLE
When I close the client my saves resets

### ISSUE THREAD

**Issue by HAWAKEEN** [momo5502/boiii#627] opened 2023-05-01 13:42 UTC
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

when I close the client my saves resets completely 

### Expected Result

Maintain the client saves regularly

### Actual Result

It doesn't crush nothing of this just after quiting, when i re-open the client the progress are gone just like i installed for the first time the game

### Severity/Priority

High/Critical

**Comment by pistakilla** [comment] 2023-05-01 14:27
Duplicate of #569

**Comment by HAWAKEEN** [comment] 2023-05-02 10:54
> Duplicate of #569

And than?

**Comment by diamante0018** [comment] 2023-05-11 12:22
Duplicate of #569

**Closed by diamante0018** 2023-05-11 12:22 UTC
Labels: bug
