### ISSUE TITLE
Auto download mods

### ISSUE THREAD

**Issue by chase-f7** [momo5502/boiii#624] opened 2023-04-30 21:40 UTC
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

This might be far fetched, but maybe if its possible to auto download a mod when connecting to a public server, if its under a certain file size limit. Like minecraft.

**Comment by Dss0** [comment] 2023-05-01 10:00
duplicate.. https://github.com/momo5502/boiii/issues/185

**Comment by diamante0018** [comment] 2023-05-01 13:43
Duplicate of #185

**Closed by diamante0018** 2023-05-01 13:43 UTC
Labels: feature
